# Generated by Django 3.2.9 on 2021-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currently_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
